// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package distrov1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_DistributionVote             protoreflect.MessageDescriptor
	fd_DistributionVote_epoch       protoreflect.FieldDescriptor
	fd_DistributionVote_signer      protoreflect.FieldDescriptor
	fd_DistributionVote_merkle_root protoreflect.FieldDescriptor
)

func init() {
	file_distro_v1_state_proto_init()
	md_DistributionVote = File_distro_v1_state_proto.Messages().ByName("DistributionVote")
	fd_DistributionVote_epoch = md_DistributionVote.Fields().ByName("epoch")
	fd_DistributionVote_signer = md_DistributionVote.Fields().ByName("signer")
	fd_DistributionVote_merkle_root = md_DistributionVote.Fields().ByName("merkle_root")
}

var _ protoreflect.Message = (*fastReflection_DistributionVote)(nil)

type fastReflection_DistributionVote DistributionVote

func (x *DistributionVote) ProtoReflect() protoreflect.Message {
	return (*fastReflection_DistributionVote)(x)
}

func (x *DistributionVote) slowProtoReflect() protoreflect.Message {
	mi := &file_distro_v1_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_DistributionVote_messageType fastReflection_DistributionVote_messageType
var _ protoreflect.MessageType = fastReflection_DistributionVote_messageType{}

type fastReflection_DistributionVote_messageType struct{}

func (x fastReflection_DistributionVote_messageType) Zero() protoreflect.Message {
	return (*fastReflection_DistributionVote)(nil)
}
func (x fastReflection_DistributionVote_messageType) New() protoreflect.Message {
	return new(fastReflection_DistributionVote)
}
func (x fastReflection_DistributionVote_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_DistributionVote
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_DistributionVote) Descriptor() protoreflect.MessageDescriptor {
	return md_DistributionVote
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_DistributionVote) Type() protoreflect.MessageType {
	return _fastReflection_DistributionVote_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_DistributionVote) New() protoreflect.Message {
	return new(fastReflection_DistributionVote)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_DistributionVote) Interface() protoreflect.ProtoMessage {
	return (*DistributionVote)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_DistributionVote) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Epoch != int64(0) {
		value := protoreflect.ValueOfInt64(x.Epoch)
		if !f(fd_DistributionVote_epoch, value) {
			return
		}
	}
	if x.Signer != "" {
		value := protoreflect.ValueOfString(x.Signer)
		if !f(fd_DistributionVote_signer, value) {
			return
		}
	}
	if len(x.MerkleRoot) != 0 {
		value := protoreflect.ValueOfBytes(x.MerkleRoot)
		if !f(fd_DistributionVote_merkle_root, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_DistributionVote) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "distro.v1.DistributionVote.epoch":
		return x.Epoch != int64(0)
	case "distro.v1.DistributionVote.signer":
		return x.Signer != ""
	case "distro.v1.DistributionVote.merkle_root":
		return len(x.MerkleRoot) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.DistributionVote"))
		}
		panic(fmt.Errorf("message distro.v1.DistributionVote does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DistributionVote) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "distro.v1.DistributionVote.epoch":
		x.Epoch = int64(0)
	case "distro.v1.DistributionVote.signer":
		x.Signer = ""
	case "distro.v1.DistributionVote.merkle_root":
		x.MerkleRoot = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.DistributionVote"))
		}
		panic(fmt.Errorf("message distro.v1.DistributionVote does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_DistributionVote) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "distro.v1.DistributionVote.epoch":
		value := x.Epoch
		return protoreflect.ValueOfInt64(value)
	case "distro.v1.DistributionVote.signer":
		value := x.Signer
		return protoreflect.ValueOfString(value)
	case "distro.v1.DistributionVote.merkle_root":
		value := x.MerkleRoot
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.DistributionVote"))
		}
		panic(fmt.Errorf("message distro.v1.DistributionVote does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DistributionVote) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "distro.v1.DistributionVote.epoch":
		x.Epoch = value.Int()
	case "distro.v1.DistributionVote.signer":
		x.Signer = value.Interface().(string)
	case "distro.v1.DistributionVote.merkle_root":
		x.MerkleRoot = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.DistributionVote"))
		}
		panic(fmt.Errorf("message distro.v1.DistributionVote does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DistributionVote) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "distro.v1.DistributionVote.epoch":
		panic(fmt.Errorf("field epoch of message distro.v1.DistributionVote is not mutable"))
	case "distro.v1.DistributionVote.signer":
		panic(fmt.Errorf("field signer of message distro.v1.DistributionVote is not mutable"))
	case "distro.v1.DistributionVote.merkle_root":
		panic(fmt.Errorf("field merkle_root of message distro.v1.DistributionVote is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.DistributionVote"))
		}
		panic(fmt.Errorf("message distro.v1.DistributionVote does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_DistributionVote) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "distro.v1.DistributionVote.epoch":
		return protoreflect.ValueOfInt64(int64(0))
	case "distro.v1.DistributionVote.signer":
		return protoreflect.ValueOfString("")
	case "distro.v1.DistributionVote.merkle_root":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.DistributionVote"))
		}
		panic(fmt.Errorf("message distro.v1.DistributionVote does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_DistributionVote) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in distro.v1.DistributionVote", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_DistributionVote) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DistributionVote) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_DistributionVote) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_DistributionVote) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*DistributionVote)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Epoch != 0 {
			n += 1 + runtime.Sov(uint64(x.Epoch))
		}
		l = len(x.Signer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MerkleRoot)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*DistributionVote)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.MerkleRoot) > 0 {
			i -= len(x.MerkleRoot)
			copy(dAtA[i:], x.MerkleRoot)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MerkleRoot)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Signer) > 0 {
			i -= len(x.Signer)
			copy(dAtA[i:], x.Signer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Signer)))
			i--
			dAtA[i] = 0x12
		}
		if x.Epoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Epoch))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*DistributionVote)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DistributionVote: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DistributionVote: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
				}
				x.Epoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Epoch |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Signer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MerkleRoot = append(x.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
				if x.MerkleRoot == nil {
					x.MerkleRoot = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_EpochDistribution                     protoreflect.MessageDescriptor
	fd_EpochDistribution_epoch               protoreflect.FieldDescriptor
	fd_EpochDistribution_merkle_root         protoreflect.FieldDescriptor
	fd_EpochDistribution_status              protoreflect.FieldDescriptor
	fd_EpochDistribution_license_tally       protoreflect.FieldDescriptor
	fd_EpochDistribution_stake_tally         protoreflect.FieldDescriptor
	fd_EpochDistribution_finalized_height    protoreflect.FieldDescriptor
	fd_EpochDistribution_pending_since_epoch protoreflect.FieldDescriptor
	fd_EpochDistribution_challenger          protoreflect.FieldDescriptor
	fd_EpochDistribution_challenge_bond      protoreflect.FieldDescriptor
)

func init() {
	file_distro_v1_state_proto_init()
	md_EpochDistribution = File_distro_v1_state_proto.Messages().ByName("EpochDistribution")
	fd_EpochDistribution_epoch = md_EpochDistribution.Fields().ByName("epoch")
	fd_EpochDistribution_merkle_root = md_EpochDistribution.Fields().ByName("merkle_root")
	fd_EpochDistribution_status = md_EpochDistribution.Fields().ByName("status")
	fd_EpochDistribution_license_tally = md_EpochDistribution.Fields().ByName("license_tally")
	fd_EpochDistribution_stake_tally = md_EpochDistribution.Fields().ByName("stake_tally")
	fd_EpochDistribution_finalized_height = md_EpochDistribution.Fields().ByName("finalized_height")
	fd_EpochDistribution_pending_since_epoch = md_EpochDistribution.Fields().ByName("pending_since_epoch")
	fd_EpochDistribution_challenger = md_EpochDistribution.Fields().ByName("challenger")
	fd_EpochDistribution_challenge_bond = md_EpochDistribution.Fields().ByName("challenge_bond")
}

var _ protoreflect.Message = (*fastReflection_EpochDistribution)(nil)

type fastReflection_EpochDistribution EpochDistribution

func (x *EpochDistribution) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EpochDistribution)(x)
}

func (x *EpochDistribution) slowProtoReflect() protoreflect.Message {
	mi := &file_distro_v1_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EpochDistribution_messageType fastReflection_EpochDistribution_messageType
var _ protoreflect.MessageType = fastReflection_EpochDistribution_messageType{}

type fastReflection_EpochDistribution_messageType struct{}

func (x fastReflection_EpochDistribution_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EpochDistribution)(nil)
}
func (x fastReflection_EpochDistribution_messageType) New() protoreflect.Message {
	return new(fastReflection_EpochDistribution)
}
func (x fastReflection_EpochDistribution_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EpochDistribution
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EpochDistribution) Descriptor() protoreflect.MessageDescriptor {
	return md_EpochDistribution
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EpochDistribution) Type() protoreflect.MessageType {
	return _fastReflection_EpochDistribution_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EpochDistribution) New() protoreflect.Message {
	return new(fastReflection_EpochDistribution)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EpochDistribution) Interface() protoreflect.ProtoMessage {
	return (*EpochDistribution)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EpochDistribution) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Epoch != int64(0) {
		value := protoreflect.ValueOfInt64(x.Epoch)
		if !f(fd_EpochDistribution_epoch, value) {
			return
		}
	}
	if len(x.MerkleRoot) != 0 {
		value := protoreflect.ValueOfBytes(x.MerkleRoot)
		if !f(fd_EpochDistribution_merkle_root, value) {
			return
		}
	}
	if x.Status != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Status))
		if !f(fd_EpochDistribution_status, value) {
			return
		}
	}
	if x.LicenseTally != "" {
		value := protoreflect.ValueOfString(x.LicenseTally)
		if !f(fd_EpochDistribution_license_tally, value) {
			return
		}
	}
	if x.StakeTally != "" {
		value := protoreflect.ValueOfString(x.StakeTally)
		if !f(fd_EpochDistribution_stake_tally, value) {
			return
		}
	}
	if x.FinalizedHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.FinalizedHeight)
		if !f(fd_EpochDistribution_finalized_height, value) {
			return
		}
	}
	if x.PendingSinceEpoch != int64(0) {
		value := protoreflect.ValueOfInt64(x.PendingSinceEpoch)
		if !f(fd_EpochDistribution_pending_since_epoch, value) {
			return
		}
	}
	if x.Challenger != "" {
		value := protoreflect.ValueOfString(x.Challenger)
		if !f(fd_EpochDistribution_challenger, value) {
			return
		}
	}
	if x.ChallengeBond != "" {
		value := protoreflect.ValueOfString(x.ChallengeBond)
		if !f(fd_EpochDistribution_challenge_bond, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EpochDistribution) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "distro.v1.EpochDistribution.epoch":
		return x.Epoch != int64(0)
	case "distro.v1.EpochDistribution.merkle_root":
		return len(x.MerkleRoot) != 0
	case "distro.v1.EpochDistribution.status":
		return x.Status != 0
	case "distro.v1.EpochDistribution.license_tally":
		return x.LicenseTally != ""
	case "distro.v1.EpochDistribution.stake_tally":
		return x.StakeTally != ""
	case "distro.v1.EpochDistribution.finalized_height":
		return x.FinalizedHeight != int64(0)
	case "distro.v1.EpochDistribution.pending_since_epoch":
		return x.PendingSinceEpoch != int64(0)
	case "distro.v1.EpochDistribution.challenger":
		return x.Challenger != ""
	case "distro.v1.EpochDistribution.challenge_bond":
		return x.ChallengeBond != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.EpochDistribution"))
		}
		panic(fmt.Errorf("message distro.v1.EpochDistribution does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochDistribution) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "distro.v1.EpochDistribution.epoch":
		x.Epoch = int64(0)
	case "distro.v1.EpochDistribution.merkle_root":
		x.MerkleRoot = nil
	case "distro.v1.EpochDistribution.status":
		x.Status = 0
	case "distro.v1.EpochDistribution.license_tally":
		x.LicenseTally = ""
	case "distro.v1.EpochDistribution.stake_tally":
		x.StakeTally = ""
	case "distro.v1.EpochDistribution.finalized_height":
		x.FinalizedHeight = int64(0)
	case "distro.v1.EpochDistribution.pending_since_epoch":
		x.PendingSinceEpoch = int64(0)
	case "distro.v1.EpochDistribution.challenger":
		x.Challenger = ""
	case "distro.v1.EpochDistribution.challenge_bond":
		x.ChallengeBond = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.EpochDistribution"))
		}
		panic(fmt.Errorf("message distro.v1.EpochDistribution does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EpochDistribution) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "distro.v1.EpochDistribution.epoch":
		value := x.Epoch
		return protoreflect.ValueOfInt64(value)
	case "distro.v1.EpochDistribution.merkle_root":
		value := x.MerkleRoot
		return protoreflect.ValueOfBytes(value)
	case "distro.v1.EpochDistribution.status":
		value := x.Status
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "distro.v1.EpochDistribution.license_tally":
		value := x.LicenseTally
		return protoreflect.ValueOfString(value)
	case "distro.v1.EpochDistribution.stake_tally":
		value := x.StakeTally
		return protoreflect.ValueOfString(value)
	case "distro.v1.EpochDistribution.finalized_height":
		value := x.FinalizedHeight
		return protoreflect.ValueOfInt64(value)
	case "distro.v1.EpochDistribution.pending_since_epoch":
		value := x.PendingSinceEpoch
		return protoreflect.ValueOfInt64(value)
	case "distro.v1.EpochDistribution.challenger":
		value := x.Challenger
		return protoreflect.ValueOfString(value)
	case "distro.v1.EpochDistribution.challenge_bond":
		value := x.ChallengeBond
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.EpochDistribution"))
		}
		panic(fmt.Errorf("message distro.v1.EpochDistribution does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochDistribution) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "distro.v1.EpochDistribution.epoch":
		x.Epoch = value.Int()
	case "distro.v1.EpochDistribution.merkle_root":
		x.MerkleRoot = value.Bytes()
	case "distro.v1.EpochDistribution.status":
		x.Status = (DistributionStatus)(value.Enum())
	case "distro.v1.EpochDistribution.license_tally":
		x.LicenseTally = value.Interface().(string)
	case "distro.v1.EpochDistribution.stake_tally":
		x.StakeTally = value.Interface().(string)
	case "distro.v1.EpochDistribution.finalized_height":
		x.FinalizedHeight = value.Int()
	case "distro.v1.EpochDistribution.pending_since_epoch":
		x.PendingSinceEpoch = value.Int()
	case "distro.v1.EpochDistribution.challenger":
		x.Challenger = value.Interface().(string)
	case "distro.v1.EpochDistribution.challenge_bond":
		x.ChallengeBond = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.EpochDistribution"))
		}
		panic(fmt.Errorf("message distro.v1.EpochDistribution does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochDistribution) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "distro.v1.EpochDistribution.epoch":
		panic(fmt.Errorf("field epoch of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.merkle_root":
		panic(fmt.Errorf("field merkle_root of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.status":
		panic(fmt.Errorf("field status of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.license_tally":
		panic(fmt.Errorf("field license_tally of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.stake_tally":
		panic(fmt.Errorf("field stake_tally of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.finalized_height":
		panic(fmt.Errorf("field finalized_height of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.pending_since_epoch":
		panic(fmt.Errorf("field pending_since_epoch of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.challenger":
		panic(fmt.Errorf("field challenger of message distro.v1.EpochDistribution is not mutable"))
	case "distro.v1.EpochDistribution.challenge_bond":
		panic(fmt.Errorf("field challenge_bond of message distro.v1.EpochDistribution is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.EpochDistribution"))
		}
		panic(fmt.Errorf("message distro.v1.EpochDistribution does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EpochDistribution) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "distro.v1.EpochDistribution.epoch":
		return protoreflect.ValueOfInt64(int64(0))
	case "distro.v1.EpochDistribution.merkle_root":
		return protoreflect.ValueOfBytes(nil)
	case "distro.v1.EpochDistribution.status":
		return protoreflect.ValueOfEnum(0)
	case "distro.v1.EpochDistribution.license_tally":
		return protoreflect.ValueOfString("")
	case "distro.v1.EpochDistribution.stake_tally":
		return protoreflect.ValueOfString("")
	case "distro.v1.EpochDistribution.finalized_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "distro.v1.EpochDistribution.pending_since_epoch":
		return protoreflect.ValueOfInt64(int64(0))
	case "distro.v1.EpochDistribution.challenger":
		return protoreflect.ValueOfString("")
	case "distro.v1.EpochDistribution.challenge_bond":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.EpochDistribution"))
		}
		panic(fmt.Errorf("message distro.v1.EpochDistribution does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EpochDistribution) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in distro.v1.EpochDistribution", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EpochDistribution) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochDistribution) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EpochDistribution) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EpochDistribution) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EpochDistribution)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Epoch != 0 {
			n += 1 + runtime.Sov(uint64(x.Epoch))
		}
		l = len(x.MerkleRoot)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Status != 0 {
			n += 1 + runtime.Sov(uint64(x.Status))
		}
		l = len(x.LicenseTally)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StakeTally)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.FinalizedHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.FinalizedHeight))
		}
		if x.PendingSinceEpoch != 0 {
			n += 1 + runtime.Sov(uint64(x.PendingSinceEpoch))
		}
		l = len(x.Challenger)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ChallengeBond)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EpochDistribution)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ChallengeBond) > 0 {
			i -= len(x.ChallengeBond)
			copy(dAtA[i:], x.ChallengeBond)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ChallengeBond)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.Challenger) > 0 {
			i -= len(x.Challenger)
			copy(dAtA[i:], x.Challenger)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Challenger)))
			i--
			dAtA[i] = 0x42
		}
		if x.PendingSinceEpoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PendingSinceEpoch))
			i--
			dAtA[i] = 0x38
		}
		if x.FinalizedHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.FinalizedHeight))
			i--
			dAtA[i] = 0x30
		}
		if len(x.StakeTally) > 0 {
			i -= len(x.StakeTally)
			copy(dAtA[i:], x.StakeTally)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StakeTally)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.LicenseTally) > 0 {
			i -= len(x.LicenseTally)
			copy(dAtA[i:], x.LicenseTally)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LicenseTally)))
			i--
			dAtA[i] = 0x22
		}
		if x.Status != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Status))
			i--
			dAtA[i] = 0x18
		}
		if len(x.MerkleRoot) > 0 {
			i -= len(x.MerkleRoot)
			copy(dAtA[i:], x.MerkleRoot)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MerkleRoot)))
			i--
			dAtA[i] = 0x12
		}
		if x.Epoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Epoch))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EpochDistribution)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EpochDistribution: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EpochDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
				}
				x.Epoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Epoch |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MerkleRoot = append(x.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
				if x.MerkleRoot == nil {
					x.MerkleRoot = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				x.Status = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Status |= DistributionStatus(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LicenseTally", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LicenseTally = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StakeTally", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StakeTally = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
				}
				x.FinalizedHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.FinalizedHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PendingSinceEpoch", wireType)
				}
				x.PendingSinceEpoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PendingSinceEpoch |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Challenger = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChallengeBond", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ChallengeBond = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_ClaimedReward_2_list)(nil)

type _ClaimedReward_2_list struct {
	list *[]uint64
}

func (x *_ClaimedReward_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_ClaimedReward_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfUint64((*x.list)[i])
}

func (x *_ClaimedReward_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Uint()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_ClaimedReward_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Uint()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_ClaimedReward_2_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message ClaimedReward at list field Nonces as it is not of Message kind"))
}

func (x *_ClaimedReward_2_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_ClaimedReward_2_list) NewElement() protoreflect.Value {
	v := uint64(0)
	return protoreflect.ValueOfUint64(v)
}

func (x *_ClaimedReward_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_ClaimedReward        protoreflect.MessageDescriptor
	fd_ClaimedReward_epoch  protoreflect.FieldDescriptor
	fd_ClaimedReward_nonces protoreflect.FieldDescriptor
)

func init() {
	file_distro_v1_state_proto_init()
	md_ClaimedReward = File_distro_v1_state_proto.Messages().ByName("ClaimedReward")
	fd_ClaimedReward_epoch = md_ClaimedReward.Fields().ByName("epoch")
	fd_ClaimedReward_nonces = md_ClaimedReward.Fields().ByName("nonces")
}

var _ protoreflect.Message = (*fastReflection_ClaimedReward)(nil)

type fastReflection_ClaimedReward ClaimedReward

func (x *ClaimedReward) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ClaimedReward)(x)
}

func (x *ClaimedReward) slowProtoReflect() protoreflect.Message {
	mi := &file_distro_v1_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ClaimedReward_messageType fastReflection_ClaimedReward_messageType
var _ protoreflect.MessageType = fastReflection_ClaimedReward_messageType{}

type fastReflection_ClaimedReward_messageType struct{}

func (x fastReflection_ClaimedReward_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ClaimedReward)(nil)
}
func (x fastReflection_ClaimedReward_messageType) New() protoreflect.Message {
	return new(fastReflection_ClaimedReward)
}
func (x fastReflection_ClaimedReward_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ClaimedReward
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ClaimedReward) Descriptor() protoreflect.MessageDescriptor {
	return md_ClaimedReward
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ClaimedReward) Type() protoreflect.MessageType {
	return _fastReflection_ClaimedReward_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ClaimedReward) New() protoreflect.Message {
	return new(fastReflection_ClaimedReward)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ClaimedReward) Interface() protoreflect.ProtoMessage {
	return (*ClaimedReward)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ClaimedReward) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Epoch != int64(0) {
		value := protoreflect.ValueOfInt64(x.Epoch)
		if !f(fd_ClaimedReward_epoch, value) {
			return
		}
	}
	if len(x.Nonces) != 0 {
		value := protoreflect.ValueOfList(&_ClaimedReward_2_list{list: &x.Nonces})
		if !f(fd_ClaimedReward_nonces, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ClaimedReward) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "distro.v1.ClaimedReward.epoch":
		return x.Epoch != int64(0)
	case "distro.v1.ClaimedReward.nonces":
		return len(x.Nonces) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.ClaimedReward"))
		}
		panic(fmt.Errorf("message distro.v1.ClaimedReward does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClaimedReward) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "distro.v1.ClaimedReward.epoch":
		x.Epoch = int64(0)
	case "distro.v1.ClaimedReward.nonces":
		x.Nonces = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.ClaimedReward"))
		}
		panic(fmt.Errorf("message distro.v1.ClaimedReward does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ClaimedReward) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "distro.v1.ClaimedReward.epoch":
		value := x.Epoch
		return protoreflect.ValueOfInt64(value)
	case "distro.v1.ClaimedReward.nonces":
		if len(x.Nonces) == 0 {
			return protoreflect.ValueOfList(&_ClaimedReward_2_list{})
		}
		listValue := &_ClaimedReward_2_list{list: &x.Nonces}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.ClaimedReward"))
		}
		panic(fmt.Errorf("message distro.v1.ClaimedReward does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClaimedReward) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "distro.v1.ClaimedReward.epoch":
		x.Epoch = value.Int()
	case "distro.v1.ClaimedReward.nonces":
		lv := value.List()
		clv := lv.(*_ClaimedReward_2_list)
		x.Nonces = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.ClaimedReward"))
		}
		panic(fmt.Errorf("message distro.v1.ClaimedReward does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClaimedReward) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "distro.v1.ClaimedReward.nonces":
		if x.Nonces == nil {
			x.Nonces = []uint64{}
		}
		value := &_ClaimedReward_2_list{list: &x.Nonces}
		return protoreflect.ValueOfList(value)
	case "distro.v1.ClaimedReward.epoch":
		panic(fmt.Errorf("field epoch of message distro.v1.ClaimedReward is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.ClaimedReward"))
		}
		panic(fmt.Errorf("message distro.v1.ClaimedReward does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ClaimedReward) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "distro.v1.ClaimedReward.epoch":
		return protoreflect.ValueOfInt64(int64(0))
	case "distro.v1.ClaimedReward.nonces":
		list := []uint64{}
		return protoreflect.ValueOfList(&_ClaimedReward_2_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: distro.v1.ClaimedReward"))
		}
		panic(fmt.Errorf("message distro.v1.ClaimedReward does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ClaimedReward) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in distro.v1.ClaimedReward", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ClaimedReward) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ClaimedReward) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ClaimedReward) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ClaimedReward) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ClaimedReward)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Epoch != 0 {
			n += 1 + runtime.Sov(uint64(x.Epoch))
		}
		if len(x.Nonces) > 0 {
			l = 0
			for _, e := range x.Nonces {
				l += runtime.Sov(uint64(e))
			}
			n += 1 + runtime.Sov(uint64(l)) + l
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ClaimedReward)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Nonces) > 0 {
			var pksize2 int
			for _, num := range x.Nonces {
				pksize2 += runtime.Sov(uint64(num))
			}
			i -= pksize2
			j1 := i
			for _, num := range x.Nonces {
				for num >= 1<<7 {
					dAtA[j1] = uint8(uint64(num)&0x7f | 0x80)
					num >>= 7
					j1++
				}
				dAtA[j1] = uint8(num)
				j1++
			}
			i = runtime.EncodeVarint(dAtA, i, uint64(pksize2))
			i--
			dAtA[i] = 0x12
		}
		if x.Epoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Epoch))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ClaimedReward)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ClaimedReward: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ClaimedReward: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
				}
				x.Epoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Epoch |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType == 0 {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
						}
						if iNdEx >= l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					x.Nonces = append(x.Nonces, v)
				} else if wireType == 2 {
					var packedLen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
						}
						if iNdEx >= l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						packedLen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if packedLen < 0 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
					}
					postIndex := iNdEx + packedLen
					if postIndex < 0 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
					}
					if postIndex > l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					var elementCount int
					var count int
					for _, integer := range dAtA[iNdEx:postIndex] {
						if integer < 128 {
							count++
						}
					}
					elementCount = count
					if elementCount != 0 && len(x.Nonces) == 0 {
						x.Nonces = make([]uint64, 0, elementCount)
					}
					for iNdEx < postIndex {
						var v uint64
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							v |= uint64(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
						x.Nonces = append(x.Nonces, v)
					}
				} else {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Nonces", wireType)
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: distro/v1/state.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DistributionStatus is the lifecycle state of an epoch's distribution.
//
// VOTING -> PENDING -> LIVE is the happy path. A licensed holder may challenge a
// PENDING distribution within the review-delay window, moving it to
// UNDER_REVIEW, which reopens voting; the re-tally resolves the challenge.
type DistributionStatus int32

const (
	// DISTRIBUTION_STATUS_VOTING means votes are accumulating; no consensus yet.
	DistributionStatus_DISTRIBUTION_STATUS_VOTING DistributionStatus = 0
	// DISTRIBUTION_STATUS_LIVE means the canonical root is claimable.
	DistributionStatus_DISTRIBUTION_STATUS_LIVE DistributionStatus = 1
	// DISTRIBUTION_STATUS_PENDING means consensus was reached and the distribution
	// is in the review-delay window, auto-promoting to LIVE if unchallenged.
	DistributionStatus_DISTRIBUTION_STATUS_PENDING DistributionStatus = 2
	// DISTRIBUTION_STATUS_UNDER_REVIEW means a licensed holder challenged the
	// pending root; voting has reopened and the re-tally will resolve it.
	DistributionStatus_DISTRIBUTION_STATUS_UNDER_REVIEW DistributionStatus = 3
)

// Enum value maps for DistributionStatus.
var (
	DistributionStatus_name = map[int32]string{
		0: "DISTRIBUTION_STATUS_VOTING",
		1: "DISTRIBUTION_STATUS_LIVE",
		2: "DISTRIBUTION_STATUS_PENDING",
		3: "DISTRIBUTION_STATUS_UNDER_REVIEW",
	}
	DistributionStatus_value = map[string]int32{
		"DISTRIBUTION_STATUS_VOTING":       0,
		"DISTRIBUTION_STATUS_LIVE":         1,
		"DISTRIBUTION_STATUS_PENDING":      2,
		"DISTRIBUTION_STATUS_UNDER_REVIEW": 3,
	}
)

func (x DistributionStatus) Enum() *DistributionStatus {
	p := new(DistributionStatus)
	*p = x
	return p
}

func (x DistributionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistributionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_distro_v1_state_proto_enumTypes[0].Descriptor()
}

func (DistributionStatus) Type() protoreflect.EnumType {
	return &file_distro_v1_state_proto_enumTypes[0]
}

func (x DistributionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistributionStatus.Descriptor instead.
func (DistributionStatus) EnumDescriptor() ([]byte, []int) {
	return file_distro_v1_state_proto_rawDescGZIP(), []int{0}
}

// DistributionVote is a single node's submitted merkle root for an epoch.
// Stored (and retained) keyed by (epoch, signer).
type DistributionVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch      int64  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Signer     string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	MerkleRoot []byte `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
}

func (x *DistributionVote) Reset() {
	*x = DistributionVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distro_v1_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributionVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionVote) ProtoMessage() {}

// Deprecated: Use DistributionVote.ProtoReflect.Descriptor instead.
func (*DistributionVote) Descriptor() ([]byte, []int) {
	return file_distro_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *DistributionVote) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *DistributionVote) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *DistributionVote) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

// EpochDistribution is the canonical/finalized result for an epoch (day).
type EpochDistribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch      int64              `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	MerkleRoot []byte             `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Status     DistributionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=distro.v1.DistributionStatus" json:"status,omitempty"`
	// license_tally / stake_tally record the winning root's fractions at finalization.
	LicenseTally string `protobuf:"bytes,4,opt,name=license_tally,json=licenseTally,proto3" json:"license_tally,omitempty"`
	StakeTally   string `protobuf:"bytes,5,opt,name=stake_tally,json=stakeTally,proto3" json:"stake_tally,omitempty"`
	// finalized_height is the block height at which the epoch went LIVE.
	FinalizedHeight int64 `protobuf:"varint,6,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	// pending_since_epoch is the epoch number at which this distribution entered
	// PENDING; used to measure the review-delay window.
	PendingSinceEpoch int64 `protobuf:"varint,7,opt,name=pending_since_epoch,json=pendingSinceEpoch,proto3" json:"pending_since_epoch,omitempty"`
	// challenger is the address that placed this distribution UNDER_REVIEW (empty
	// otherwise). Set while UNDER_REVIEW so the bond can be refunded or burned.
	Challenger string `protobuf:"bytes,8,opt,name=challenger,proto3" json:"challenger,omitempty"`
	// challenge_bond is the amount (in the module denom) escrowed by the
	// challenger while UNDER_REVIEW.
	ChallengeBond string `protobuf:"bytes,9,opt,name=challenge_bond,json=challengeBond,proto3" json:"challenge_bond,omitempty"`
}

func (x *EpochDistribution) Reset() {
	*x = EpochDistribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distro_v1_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochDistribution) ProtoMessage() {}

// Deprecated: Use EpochDistribution.ProtoReflect.Descriptor instead.
func (*EpochDistribution) Descriptor() ([]byte, []int) {
	return file_distro_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *EpochDistribution) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochDistribution) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *EpochDistribution) GetStatus() DistributionStatus {
	if x != nil {
		return x.Status
	}
	return DistributionStatus_DISTRIBUTION_STATUS_VOTING
}

func (x *EpochDistribution) GetLicenseTally() string {
	if x != nil {
		return x.LicenseTally
	}
	return ""
}

func (x *EpochDistribution) GetStakeTally() string {
	if x != nil {
		return x.StakeTally
	}
	return ""
}

func (x *EpochDistribution) GetFinalizedHeight() int64 {
	if x != nil {
		return x.FinalizedHeight
	}
	return 0
}

func (x *EpochDistribution) GetPendingSinceEpoch() int64 {
	if x != nil {
		return x.PendingSinceEpoch
	}
	return 0
}

func (x *EpochDistribution) GetChallenger() string {
	if x != nil {
		return x.Challenger
	}
	return ""
}

func (x *EpochDistribution) GetChallengeBond() string {
	if x != nil {
		return x.ChallengeBond
	}
	return ""
}

// ClaimedReward is the genesis representation of the claimed nonces for an epoch.
type ClaimedReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch  int64    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Nonces []uint64 `protobuf:"varint,2,rep,packed,name=nonces,proto3" json:"nonces,omitempty"`
}

func (x *ClaimedReward) Reset() {
	*x = ClaimedReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distro_v1_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimedReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimedReward) ProtoMessage() {}

// Deprecated: Use ClaimedReward.ProtoReflect.Descriptor instead.
func (*ClaimedReward) Descriptor() ([]byte, []int) {
	return file_distro_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimedReward) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ClaimedReward) GetNonces() []uint64 {
	if x != nil {
		return x.Nonces
	}
	return nil
}

var File_distro_v1_state_proto protoreflect.FileDescriptor

var file_distro_v1_state_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x30, 0x0a,
	0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2,
	0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74,
	0x22, 0x83, 0x03, 0x0a, 0x11, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b,
	0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f,
	0x74, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x6b, 0x65, 0x5f, 0x74, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x6b, 0x65, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x11, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x6e, 0x63, 0x65,
	0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x38, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x62, 0x6f, 0x6e,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x42, 0x6f, 0x6e, 0x64, 0x22, 0x3d, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65,
	0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x73, 0x2a, 0x9f, 0x01, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a,
	0x44, 0x49, 0x53, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x56, 0x4f, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18,
	0x44, 0x49, 0x53, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x49,
	0x53, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x44,
	0x49, 0x53, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10,
	0x03, 0x1a, 0x04, 0x88, 0xa3, 0x1e, 0x00, 0x42, 0x9c, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x53, 0x6d, 0x61, 0x72, 0x74,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x73, 0x63, 0x2f, 0x76, 0x33, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x6f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x44, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x15, 0x44, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_distro_v1_state_proto_rawDescOnce sync.Once
	file_distro_v1_state_proto_rawDescData = file_distro_v1_state_proto_rawDesc
)

func file_distro_v1_state_proto_rawDescGZIP() []byte {
	file_distro_v1_state_proto_rawDescOnce.Do(func() {
		file_distro_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_distro_v1_state_proto_rawDescData)
	})
	return file_distro_v1_state_proto_rawDescData
}

var file_distro_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distro_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_distro_v1_state_proto_goTypes = []interface{}{
	(DistributionStatus)(0),   // 0: distro.v1.DistributionStatus
	(*DistributionVote)(nil),  // 1: distro.v1.DistributionVote
	(*EpochDistribution)(nil), // 2: distro.v1.EpochDistribution
	(*ClaimedReward)(nil),     // 3: distro.v1.ClaimedReward
}
var file_distro_v1_state_proto_depIdxs = []int32{
	0, // 0: distro.v1.EpochDistribution.status:type_name -> distro.v1.DistributionStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_distro_v1_state_proto_init() }
func file_distro_v1_state_proto_init() {
	if File_distro_v1_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_distro_v1_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributionVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distro_v1_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochDistribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distro_v1_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimedReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distro_v1_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_distro_v1_state_proto_goTypes,
		DependencyIndexes: file_distro_v1_state_proto_depIdxs,
		EnumInfos:         file_distro_v1_state_proto_enumTypes,
		MessageInfos:      file_distro_v1_state_proto_msgTypes,
	}.Build()
	File_distro_v1_state_proto = out.File
	file_distro_v1_state_proto_rawDesc = nil
	file_distro_v1_state_proto_goTypes = nil
	file_distro_v1_state_proto_depIdxs = nil
}
