// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: distro/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the module genesis state
type GenesisState struct {
	// Params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// votes is the raw per-signer set of submitted distribution roots, keyed by
	// (epoch, signer). These are kept (never pruned) for audit.
	Votes []DistributionVote `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes"`
	// epoch_distributions is the canonical/finalized distribution per epoch.
	EpochDistributions []EpochDistribution `protobuf:"bytes,3,rep,name=epoch_distributions,json=epochDistributions,proto3" json:"epoch_distributions"`
	// claimed_rewards tracks the claimed reward nonces per epoch.
	ClaimedRewards []ClaimedReward `protobuf:"bytes,4,rep,name=claimed_rewards,json=claimedRewards,proto3" json:"claimed_rewards"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f02fec9499f3ab0, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetVotes() []DistributionVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *GenesisState) GetEpochDistributions() []EpochDistribution {
	if m != nil {
		return m.EpochDistributions
	}
	return nil
}

func (m *GenesisState) GetClaimedRewards() []ClaimedReward {
	if m != nil {
		return m.ClaimedRewards
	}
	return nil
}

// Params defines the set of module parameters.
type Params struct {
	MintingAddress        string `protobuf:"bytes,1,opt,name=minting_address,json=mintingAddress,proto3" json:"minting_address,omitempty"`
	ReceivingAddress      string `protobuf:"bytes,2,opt,name=receiving_address,json=receivingAddress,proto3" json:"receiving_address,omitempty"`
	Denom                 string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	MaxSupply             string `protobuf:"bytes,4,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	DistributionStartDate string `protobuf:"bytes,5,opt,name=distribution_start_date,json=distributionStartDate,proto3" json:"distribution_start_date,omitempty"`
	MonthsInHalvingPeriod uint64 `protobuf:"varint,6,opt,name=months_in_halving_period,json=monthsInHalvingPeriod,proto3" json:"months_in_halving_period,omitempty"`
	// distribution_license_type_id is the x/licenses LicenseType id a signer must
	// hold (with >= 1 active license) to submit a distribution root.
	DistributionLicenseTypeId string `protobuf:"bytes,7,opt,name=distribution_license_type_id,json=distributionLicenseTypeId,proto3" json:"distribution_license_type_id,omitempty"`
	// license_tally_threshold is the fraction (0,1] of license weight a root must
	// reach to pass the license-based tally. Default "0.667".
	LicenseTallyThreshold string `protobuf:"bytes,8,opt,name=license_tally_threshold,json=licenseTallyThreshold,proto3" json:"license_tally_threshold,omitempty"`
	// stake_tally_threshold is the fraction (0,1] of bonded stake a root must
	// reach to pass the stake-based tally. Default "0.667".
	StakeTallyThreshold string `protobuf:"bytes,9,opt,name=stake_tally_threshold,json=stakeTallyThreshold,proto3" json:"stake_tally_threshold,omitempty"`
	// epoch_identifier is the x/epochs identifier whose AfterEpochEnd triggers the
	// tally. Default "day".
	EpochIdentifier string `protobuf:"bytes,10,opt,name=epoch_identifier,json=epochIdentifier,proto3" json:"epoch_identifier,omitempty"`
	// distribution_review_delay is the number of epochs a distribution stays
	// PENDING (challengeable) after consensus before auto-promoting to LIVE.
	// 0 disables the delay (instant LIVE, no challenge window).
	DistributionReviewDelay uint64 `protobuf:"varint,11,opt,name=distribution_review_delay,json=distributionReviewDelay,proto3" json:"distribution_review_delay,omitempty"`
	// challenge_bond is the amount (in the module denom) a challenger must escrow
	// to place a PENDING distribution UNDER_REVIEW. Burned if the challenge is
	// frivolous (re-vote re-confirms the same root), refunded otherwise.
	ChallengeBond string `protobuf:"bytes,12,opt,name=challenge_bond,json=challengeBond,proto3" json:"challenge_bond,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f02fec9499f3ab0, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMintingAddress() string {
	if m != nil {
		return m.MintingAddress
	}
	return ""
}

func (m *Params) GetReceivingAddress() string {
	if m != nil {
		return m.ReceivingAddress
	}
	return ""
}

func (m *Params) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Params) GetMaxSupply() string {
	if m != nil {
		return m.MaxSupply
	}
	return ""
}

func (m *Params) GetDistributionStartDate() string {
	if m != nil {
		return m.DistributionStartDate
	}
	return ""
}

func (m *Params) GetMonthsInHalvingPeriod() uint64 {
	if m != nil {
		return m.MonthsInHalvingPeriod
	}
	return 0
}

func (m *Params) GetDistributionLicenseTypeId() string {
	if m != nil {
		return m.DistributionLicenseTypeId
	}
	return ""
}

func (m *Params) GetLicenseTallyThreshold() string {
	if m != nil {
		return m.LicenseTallyThreshold
	}
	return ""
}

func (m *Params) GetStakeTallyThreshold() string {
	if m != nil {
		return m.StakeTallyThreshold
	}
	return ""
}

func (m *Params) GetEpochIdentifier() string {
	if m != nil {
		return m.EpochIdentifier
	}
	return ""
}

func (m *Params) GetDistributionReviewDelay() uint64 {
	if m != nil {
		return m.DistributionReviewDelay
	}
	return 0
}

func (m *Params) GetChallengeBond() string {
	if m != nil {
		return m.ChallengeBond
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "distro.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "distro.v1.Params")
}

func init() { proto.RegisterFile("distro/v1/genesis.proto", fileDescriptor_8f02fec9499f3ab0) }

var fileDescriptor_8f02fec9499f3ab0 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0xcf, 0x4e, 0x1b, 0x3b,
	0x14, 0xc6, 0x33, 0x10, 0x72, 0x6f, 0x0c, 0x97, 0x3f, 0x86, 0xe8, 0xba, 0x94, 0x06, 0x84, 0x54,
	0x95, 0xb6, 0x52, 0x46, 0x04, 0xa9, 0x48, 0x6c, 0xaa, 0x02, 0x15, 0x45, 0x62, 0x81, 0x92, 0xa8,
	0x8b, 0x6e, 0x2c, 0x67, 0x7c, 0x9a, 0xb1, 0x3a, 0x63, 0x8f, 0x6c, 0x27, 0x90, 0x57, 0xe8, 0xaa,
	0xab, 0xae, 0xfb, 0x08, 0x7d, 0x0c, 0x96, 0x2c, 0xbb, 0x69, 0x55, 0xc1, 0xa2, 0x7d, 0x8c, 0x6a,
	0xec, 0x21, 0x0c, 0x74, 0x13, 0x4d, 0xbe, 0xef, 0x77, 0xbe, 0x73, 0xfc, 0x0f, 0xfd, 0xcf, 0x85,
	0xb1, 0x5a, 0x85, 0xa3, 0xed, 0x70, 0x00, 0x12, 0x8c, 0x30, 0xad, 0x4c, 0x2b, 0xab, 0x70, 0xdd,
	0x1b, 0xad, 0xd1, 0xf6, 0xea, 0xca, 0x40, 0x0d, 0x94, 0x53, 0xc3, 0xfc, 0xcb, 0x03, 0xab, 0x4b,
	0x2c, 0x15, 0x52, 0x85, 0xee, 0xb7, 0x90, 0x1a, 0xb7, 0x61, 0xc6, 0x32, 0x0b, 0x5e, 0xde, 0xfc,
	0x3c, 0x85, 0xe6, 0x8e, 0x7c, 0x78, 0x37, 0x97, 0x71, 0x88, 0x6a, 0x19, 0xd3, 0x2c, 0x35, 0x24,
	0xd8, 0x08, 0xb6, 0x66, 0xdb, 0x4b, 0xad, 0x49, 0xb3, 0xd6, 0xa9, 0x33, 0xf6, 0xab, 0x17, 0x3f,
	0xd6, 0x2b, 0x9d, 0x02, 0xc3, 0xbb, 0x68, 0x66, 0xa4, 0x2c, 0x18, 0x32, 0xb5, 0x31, 0xbd, 0x35,
	0xdb, 0x7e, 0x58, 0xe2, 0x0f, 0xf3, 0x2f, 0xd1, 0x1f, 0x5a, 0xa1, 0xe4, 0x5b, 0x65, 0xa1, 0xa8,
	0xf4, 0x3c, 0xee, 0xa2, 0x65, 0xc8, 0x54, 0x14, 0x53, 0x5e, 0xc2, 0x0c, 0x99, 0x76, 0x31, 0x6b,
	0xa5, 0x98, 0xd7, 0x39, 0x55, 0xce, 0x2a, 0x72, 0x30, 0xdc, 0x37, 0x0c, 0x3e, 0x42, 0x0b, 0x51,
	0xc2, 0x44, 0x0a, 0x9c, 0x6a, 0x38, 0x63, 0x9a, 0x1b, 0x52, 0x75, 0x81, 0xa4, 0x14, 0x78, 0xe0,
	0x89, 0x8e, 0x03, 0x8a, 0xb0, 0xf9, 0xa8, 0x2c, 0x9a, 0xcd, 0xef, 0x55, 0x54, 0xf3, 0xeb, 0xc5,
	0x4f, 0xd0, 0x42, 0x2a, 0xa4, 0x15, 0x72, 0x40, 0x19, 0xe7, 0x1a, 0x8c, 0xdf, 0x9b, 0x7a, 0x67,
	0xbe, 0x90, 0x5f, 0x79, 0x15, 0x3f, 0x47, 0x4b, 0x1a, 0x22, 0x10, 0xa3, 0x32, 0x3a, 0xe5, 0xd0,
	0xc5, 0x89, 0x71, 0x03, 0xaf, 0xa0, 0x19, 0x0e, 0x52, 0xa5, 0x64, 0xda, 0x01, 0xfe, 0x0f, 0x7e,
	0x84, 0x50, 0xca, 0xce, 0xa9, 0x19, 0x66, 0x59, 0x32, 0x26, 0x55, 0x67, 0xd5, 0x53, 0x76, 0xde,
	0x75, 0x02, 0x7e, 0x51, 0x5c, 0x8a, 0x62, 0xbd, 0xd4, 0x58, 0xa6, 0x2d, 0xe5, 0xcc, 0x02, 0x99,
	0x71, 0x6c, 0xa3, 0x6c, 0x77, 0x73, 0xf7, 0x30, 0x3f, 0xd5, 0x5d, 0x44, 0x52, 0x25, 0x6d, 0x6c,
	0xa8, 0x90, 0x34, 0x66, 0x89, 0x9b, 0x30, 0x03, 0x2d, 0x14, 0x27, 0xb5, 0x8d, 0x60, 0xab, 0xda,
	0x69, 0x78, 0xff, 0x58, 0xbe, 0xf1, 0xee, 0xa9, 0x33, 0xf1, 0x4b, 0xb4, 0x76, 0xa7, 0x61, 0x22,
	0x22, 0x90, 0x06, 0xa8, 0x1d, 0x67, 0x40, 0x05, 0x27, 0xff, 0xb8, 0xae, 0x0f, 0xca, 0xcc, 0x89,
	0x47, 0x7a, 0xe3, 0x0c, 0x8e, 0x79, 0x3e, 0xf1, 0xa4, 0x86, 0x25, 0xc9, 0x98, 0xda, 0x58, 0x83,
	0x89, 0x55, 0xc2, 0xc9, 0xbf, 0x7e, 0xe2, 0xc2, 0xee, 0xe5, 0x6e, 0xef, 0xc6, 0xc4, 0x6d, 0xd4,
	0x30, 0x96, 0x7d, 0xf8, 0xbb, 0xaa, 0xee, 0xaa, 0x96, 0x9d, 0x79, 0xaf, 0xe6, 0x29, 0x5a, 0xf4,
	0x37, 0x4a, 0x70, 0x90, 0x56, 0xbc, 0x17, 0xa0, 0x09, 0x72, 0xf8, 0x82, 0xd3, 0x8f, 0x27, 0x32,
	0xde, 0x43, 0x77, 0x66, 0xa6, 0x1a, 0x46, 0x02, 0xce, 0x28, 0x87, 0x84, 0x8d, 0xc9, 0xac, 0xdb,
	0x91, 0x3b, 0x3b, 0xdd, 0x71, 0xfe, 0x61, 0x6e, 0xe3, 0xc7, 0x68, 0x3e, 0x8a, 0x59, 0x92, 0x80,
	0x1c, 0x00, 0xed, 0x2b, 0xc9, 0xc9, 0x9c, 0x6b, 0xf2, 0xdf, 0x44, 0xdd, 0x57, 0x92, 0xef, 0xad,
	0xfd, 0xfe, 0xb2, 0x1e, 0x7c, 0xfc, 0xf5, 0xf5, 0xd9, 0xb2, 0x35, 0x51, 0x78, 0x1e, 0x16, 0x0f,
	0xd0, 0x3f, 0x9b, 0xfd, 0x93, 0x8b, 0xab, 0x66, 0x70, 0x79, 0xd5, 0x0c, 0x7e, 0x5e, 0x35, 0x83,
	0x4f, 0xd7, 0xcd, 0xca, 0xe5, 0x75, 0xb3, 0xf2, 0xed, 0xba, 0x59, 0x79, 0xd7, 0x1e, 0x08, 0x1b,
	0x0f, 0xfb, 0xad, 0x48, 0xa5, 0x61, 0x4f, 0x0f, 0x8d, 0x05, 0xde, 0x4d, 0x99, 0xb6, 0x07, 0x31,
	0x13, 0x32, 0xcc, 0xb3, 0x46, 0x3b, 0xb7, 0x71, 0xf9, 0x41, 0x98, 0x7e, 0xcd, 0xbd, 0xe6, 0x9d,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x1a, 0xab, 0x7e, 0x33, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MintingAddress != that1.MintingAddress {
		return false
	}
	if this.ReceivingAddress != that1.ReceivingAddress {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.MaxSupply != that1.MaxSupply {
		return false
	}
	if this.DistributionStartDate != that1.DistributionStartDate {
		return false
	}
	if this.MonthsInHalvingPeriod != that1.MonthsInHalvingPeriod {
		return false
	}
	if this.DistributionLicenseTypeId != that1.DistributionLicenseTypeId {
		return false
	}
	if this.LicenseTallyThreshold != that1.LicenseTallyThreshold {
		return false
	}
	if this.StakeTallyThreshold != that1.StakeTallyThreshold {
		return false
	}
	if this.EpochIdentifier != that1.EpochIdentifier {
		return false
	}
	if this.DistributionReviewDelay != that1.DistributionReviewDelay {
		return false
	}
	if this.ChallengeBond != that1.ChallengeBond {
		return false
	}
	return true
}
func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClaimedRewards) > 0 {
		for iNdEx := len(m.ClaimedRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClaimedRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.EpochDistributions) > 0 {
		for iNdEx := len(m.EpochDistributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochDistributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChallengeBond) > 0 {
		i -= len(m.ChallengeBond)
		copy(dAtA[i:], m.ChallengeBond)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ChallengeBond)))
		i--
		dAtA[i] = 0x62
	}
	if m.DistributionReviewDelay != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DistributionReviewDelay))
		i--
		dAtA[i] = 0x58
	}
	if len(m.EpochIdentifier) > 0 {
		i -= len(m.EpochIdentifier)
		copy(dAtA[i:], m.EpochIdentifier)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.EpochIdentifier)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.StakeTallyThreshold) > 0 {
		i -= len(m.StakeTallyThreshold)
		copy(dAtA[i:], m.StakeTallyThreshold)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakeTallyThreshold)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.LicenseTallyThreshold) > 0 {
		i -= len(m.LicenseTallyThreshold)
		copy(dAtA[i:], m.LicenseTallyThreshold)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.LicenseTallyThreshold)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DistributionLicenseTypeId) > 0 {
		i -= len(m.DistributionLicenseTypeId)
		copy(dAtA[i:], m.DistributionLicenseTypeId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DistributionLicenseTypeId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MonthsInHalvingPeriod != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MonthsInHalvingPeriod))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DistributionStartDate) > 0 {
		i -= len(m.DistributionStartDate)
		copy(dAtA[i:], m.DistributionStartDate)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DistributionStartDate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MaxSupply) > 0 {
		i -= len(m.MaxSupply)
		copy(dAtA[i:], m.MaxSupply)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MaxSupply)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ReceivingAddress) > 0 {
		i -= len(m.ReceivingAddress)
		copy(dAtA[i:], m.ReceivingAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ReceivingAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MintingAddress) > 0 {
		i -= len(m.MintingAddress)
		copy(dAtA[i:], m.MintingAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MintingAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.EpochDistributions) > 0 {
		for _, e := range m.EpochDistributions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClaimedRewards) > 0 {
		for _, e := range m.ClaimedRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MintingAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ReceivingAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.MaxSupply)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.DistributionStartDate)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.MonthsInHalvingPeriod != 0 {
		n += 1 + sovGenesis(uint64(m.MonthsInHalvingPeriod))
	}
	l = len(m.DistributionLicenseTypeId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.LicenseTallyThreshold)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.StakeTallyThreshold)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.EpochIdentifier)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.DistributionReviewDelay != 0 {
		n += 1 + sovGenesis(uint64(m.DistributionReviewDelay))
	}
	l = len(m.ChallengeBond)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, DistributionVote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDistributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochDistributions = append(m.EpochDistributions, EpochDistribution{})
			if err := m.EpochDistributions[len(m.EpochDistributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimedRewards = append(m.ClaimedRewards, ClaimedReward{})
			if err := m.ClaimedRewards[len(m.ClaimedRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionStartDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionStartDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthsInHalvingPeriod", wireType)
			}
			m.MonthsInHalvingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthsInHalvingPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionLicenseTypeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionLicenseTypeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LicenseTallyThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LicenseTallyThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeTallyThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeTallyThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionReviewDelay", wireType)
			}
			m.DistributionReviewDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionReviewDelay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeBond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChallengeBond = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
