// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: distro/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params defines the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryDistributionRequest struct {
	// date is the distribution day in YYYY-MM-DD form.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *QueryDistributionRequest) Reset()         { *m = QueryDistributionRequest{} }
func (m *QueryDistributionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDistributionRequest) ProtoMessage()    {}
func (*QueryDistributionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{2}
}
func (m *QueryDistributionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDistributionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDistributionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDistributionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDistributionRequest.Merge(m, src)
}
func (m *QueryDistributionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDistributionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDistributionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDistributionRequest proto.InternalMessageInfo

func (m *QueryDistributionRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type QueryDistributionResponse struct {
	Distribution *Distribution `protobuf:"bytes,1,opt,name=distribution,proto3" json:"distribution,omitempty"`
}

func (m *QueryDistributionResponse) Reset()         { *m = QueryDistributionResponse{} }
func (m *QueryDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDistributionResponse) ProtoMessage()    {}
func (*QueryDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{3}
}
func (m *QueryDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDistributionResponse.Merge(m, src)
}
func (m *QueryDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDistributionResponse proto.InternalMessageInfo

func (m *QueryDistributionResponse) GetDistribution() *Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

type QueryDistributionVotesRequest struct {
	// date is the distribution day in YYYY-MM-DD form.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *QueryDistributionVotesRequest) Reset()         { *m = QueryDistributionVotesRequest{} }
func (m *QueryDistributionVotesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDistributionVotesRequest) ProtoMessage()    {}
func (*QueryDistributionVotesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{4}
}
func (m *QueryDistributionVotesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDistributionVotesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDistributionVotesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDistributionVotesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDistributionVotesRequest.Merge(m, src)
}
func (m *QueryDistributionVotesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDistributionVotesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDistributionVotesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDistributionVotesRequest proto.InternalMessageInfo

func (m *QueryDistributionVotesRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type QueryDistributionVotesResponse struct {
	Votes []DistributionVote `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes"`
}

func (m *QueryDistributionVotesResponse) Reset()         { *m = QueryDistributionVotesResponse{} }
func (m *QueryDistributionVotesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDistributionVotesResponse) ProtoMessage()    {}
func (*QueryDistributionVotesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{5}
}
func (m *QueryDistributionVotesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDistributionVotesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDistributionVotesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDistributionVotesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDistributionVotesResponse.Merge(m, src)
}
func (m *QueryDistributionVotesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDistributionVotesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDistributionVotesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDistributionVotesResponse proto.InternalMessageInfo

func (m *QueryDistributionVotesResponse) GetVotes() []DistributionVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

type QueryClaimedRequest struct {
	// date is the distribution day in YYYY-MM-DD form.
	Date  string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *QueryClaimedRequest) Reset()         { *m = QueryClaimedRequest{} }
func (m *QueryClaimedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClaimedRequest) ProtoMessage()    {}
func (*QueryClaimedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{6}
}
func (m *QueryClaimedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClaimedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClaimedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClaimedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimedRequest.Merge(m, src)
}
func (m *QueryClaimedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryClaimedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimedRequest proto.InternalMessageInfo

func (m *QueryClaimedRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *QueryClaimedRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type QueryClaimedResponse struct {
	Claimed bool `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
}

func (m *QueryClaimedResponse) Reset()         { *m = QueryClaimedResponse{} }
func (m *QueryClaimedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClaimedResponse) ProtoMessage()    {}
func (*QueryClaimedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{7}
}
func (m *QueryClaimedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClaimedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClaimedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClaimedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimedResponse.Merge(m, src)
}
func (m *QueryClaimedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryClaimedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimedResponse proto.InternalMessageInfo

func (m *QueryClaimedResponse) GetClaimed() bool {
	if m != nil {
		return m.Claimed
	}
	return false
}

type QueryClaimsByDateRequest struct {
	// date is the distribution day in YYYY-MM-DD form.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *QueryClaimsByDateRequest) Reset()         { *m = QueryClaimsByDateRequest{} }
func (m *QueryClaimsByDateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClaimsByDateRequest) ProtoMessage()    {}
func (*QueryClaimsByDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{8}
}
func (m *QueryClaimsByDateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClaimsByDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClaimsByDateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClaimsByDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimsByDateRequest.Merge(m, src)
}
func (m *QueryClaimsByDateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryClaimsByDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimsByDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimsByDateRequest proto.InternalMessageInfo

func (m *QueryClaimsByDateRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type QueryClaimsByDateResponse struct {
	// nonces are the claimed reward nonces for the day, in ascending order.
	Nonces []uint64 `protobuf:"varint,1,rep,packed,name=nonces,proto3" json:"nonces,omitempty"`
}

func (m *QueryClaimsByDateResponse) Reset()         { *m = QueryClaimsByDateResponse{} }
func (m *QueryClaimsByDateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClaimsByDateResponse) ProtoMessage()    {}
func (*QueryClaimsByDateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{9}
}
func (m *QueryClaimsByDateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClaimsByDateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClaimsByDateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClaimsByDateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimsByDateResponse.Merge(m, src)
}
func (m *QueryClaimsByDateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryClaimsByDateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimsByDateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimsByDateResponse proto.InternalMessageInfo

func (m *QueryClaimsByDateResponse) GetNonces() []uint64 {
	if m != nil {
		return m.Nonces
	}
	return nil
}

type QueryClaimTotalByCategoryRequest struct {
	// date selects the distribution by calendar day (YYYY-MM-DD).
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *QueryClaimTotalByCategoryRequest) Reset()         { *m = QueryClaimTotalByCategoryRequest{} }
func (m *QueryClaimTotalByCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClaimTotalByCategoryRequest) ProtoMessage()    {}
func (*QueryClaimTotalByCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{10}
}
func (m *QueryClaimTotalByCategoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClaimTotalByCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClaimTotalByCategoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClaimTotalByCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimTotalByCategoryRequest.Merge(m, src)
}
func (m *QueryClaimTotalByCategoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryClaimTotalByCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimTotalByCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimTotalByCategoryRequest proto.InternalMessageInfo

func (m *QueryClaimTotalByCategoryRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type QueryClaimTotalByCategoryResponse struct {
	// date is the distribution day the totals belong to.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// totals maps each reward category to its cumulative claimed amount.
	Totals map[string]string `protobuf:"bytes,2,rep,name=totals,proto3" json:"totals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *QueryClaimTotalByCategoryResponse) Reset()         { *m = QueryClaimTotalByCategoryResponse{} }
func (m *QueryClaimTotalByCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClaimTotalByCategoryResponse) ProtoMessage()    {}
func (*QueryClaimTotalByCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7e3e1b7748b0bb4, []int{11}
}
func (m *QueryClaimTotalByCategoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClaimTotalByCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClaimTotalByCategoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClaimTotalByCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimTotalByCategoryResponse.Merge(m, src)
}
func (m *QueryClaimTotalByCategoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryClaimTotalByCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimTotalByCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimTotalByCategoryResponse proto.InternalMessageInfo

func (m *QueryClaimTotalByCategoryResponse) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *QueryClaimTotalByCategoryResponse) GetTotals() map[string]string {
	if m != nil {
		return m.Totals
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "distro.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "distro.v1.QueryParamsResponse")
	proto.RegisterType((*QueryDistributionRequest)(nil), "distro.v1.QueryDistributionRequest")
	proto.RegisterType((*QueryDistributionResponse)(nil), "distro.v1.QueryDistributionResponse")
	proto.RegisterType((*QueryDistributionVotesRequest)(nil), "distro.v1.QueryDistributionVotesRequest")
	proto.RegisterType((*QueryDistributionVotesResponse)(nil), "distro.v1.QueryDistributionVotesResponse")
	proto.RegisterType((*QueryClaimedRequest)(nil), "distro.v1.QueryClaimedRequest")
	proto.RegisterType((*QueryClaimedResponse)(nil), "distro.v1.QueryClaimedResponse")
	proto.RegisterType((*QueryClaimsByDateRequest)(nil), "distro.v1.QueryClaimsByDateRequest")
	proto.RegisterType((*QueryClaimsByDateResponse)(nil), "distro.v1.QueryClaimsByDateResponse")
	proto.RegisterType((*QueryClaimTotalByCategoryRequest)(nil), "distro.v1.QueryClaimTotalByCategoryRequest")
	proto.RegisterType((*QueryClaimTotalByCategoryResponse)(nil), "distro.v1.QueryClaimTotalByCategoryResponse")
	proto.RegisterMapType((map[string]string)(nil), "distro.v1.QueryClaimTotalByCategoryResponse.TotalsEntry")
}

func init() { proto.RegisterFile("distro/v1/query.proto", fileDescriptor_b7e3e1b7748b0bb4) }

var fileDescriptor_b7e3e1b7748b0bb4 = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x8d, 0xd3, 0x34, 0x7d, 0xbd, 0xed, 0xe2, 0x75, 0x5e, 0xfa, 0x1a, 0x4c, 0xeb, 0x06, 0x53,
	0x44, 0x5a, 0xa8, 0xdd, 0x26, 0x02, 0x0a, 0x2c, 0x40, 0x69, 0xd9, 0xb1, 0x28, 0xa6, 0x42, 0xc0,
	0x26, 0x9a, 0x24, 0x83, 0x6b, 0x91, 0x78, 0x52, 0xcf, 0x24, 0xc2, 0xaa, 0x2a, 0x24, 0x24, 0xf6,
	0x48, 0xec, 0xf8, 0x02, 0xfe, 0x81, 0x2d, 0x8b, 0x2e, 0x2b, 0xb1, 0x61, 0x85, 0x50, 0xcb, 0x87,
	0x20, 0x8f, 0x27, 0xa9, 0x93, 0x38, 0xa6, 0xec, 0x66, 0xee, 0x9c, 0x7b, 0xce, 0x19, 0xdf, 0x39,
	0x32, 0xcc, 0x37, 0x1c, 0xc6, 0x3d, 0x6a, 0x76, 0x37, 0xcd, 0x83, 0x0e, 0xf1, 0x7c, 0xa3, 0xed,
	0x51, 0x4e, 0xd1, 0x74, 0x58, 0x36, 0xba, 0x9b, 0x6a, 0xce, 0xa6, 0x36, 0x15, 0x55, 0x33, 0x58,
	0x85, 0x00, 0x75, 0xd1, 0xa6, 0xd4, 0x6e, 0x12, 0x13, 0xb7, 0x1d, 0x13, 0xbb, 0x2e, 0xe5, 0x98,
	0x3b, 0xd4, 0x65, 0xf2, 0x74, 0xe1, 0x9c, 0xd5, 0x26, 0x2e, 0x61, 0x4e, 0xef, 0x20, 0x22, 0xc7,
	0x38, 0xe6, 0x24, 0x2c, 0xeb, 0x39, 0x40, 0x4f, 0x02, 0xf5, 0x5d, 0xec, 0xe1, 0x16, 0xb3, 0xc8,
	0x41, 0x87, 0x30, 0xae, 0x3f, 0x84, 0xff, 0x06, 0xaa, 0xac, 0x4d, 0x5d, 0x46, 0xd0, 0x2a, 0x64,
	0xdb, 0xa2, 0x92, 0x57, 0x0a, 0x4a, 0x71, 0xa6, 0x34, 0x67, 0xf4, 0xcd, 0x1a, 0x12, 0x2a, 0x01,
	0xba, 0x01, 0x79, 0xc1, 0xb0, 0x13, 0x00, 0x9c, 0x5a, 0x27, 0xf0, 0x28, 0xd9, 0x11, 0x82, 0x4c,
	0x03, 0x73, 0x22, 0x48, 0xa6, 0x2d, 0xb1, 0xd6, 0x9f, 0xc3, 0xa5, 0x18, 0xbc, 0xd4, 0xbd, 0x0f,
	0xb3, 0x8d, 0x48, 0x5d, 0xaa, 0x2f, 0x44, 0xd4, 0x07, 0xda, 0x06, 0xc0, 0x7a, 0x19, 0x96, 0x46,
	0x98, 0x9f, 0x51, 0x4e, 0x58, 0x92, 0x9d, 0x17, 0xa0, 0x8d, 0x6b, 0x92, 0x9e, 0xee, 0xc0, 0x64,
	0x37, 0x28, 0xe4, 0x95, 0xc2, 0x44, 0x71, 0xa6, 0x74, 0x79, 0x8c, 0x99, 0xa0, 0xa9, 0x92, 0x39,
	0xfe, 0xb1, 0x9c, 0xb2, 0x42, 0xbc, 0xfe, 0x40, 0x7e, 0xdb, 0xed, 0x26, 0x76, 0x5a, 0xa4, 0x91,
	0xe0, 0x02, 0xe5, 0x60, 0xd2, 0xa5, 0x6e, 0x9d, 0xe4, 0xd3, 0x05, 0xa5, 0x98, 0xb1, 0xc2, 0x8d,
	0xbe, 0x01, 0xb9, 0x41, 0x02, 0xe9, 0x28, 0x0f, 0x53, 0xf5, 0xb0, 0x24, 0x48, 0xfe, 0xb1, 0x7a,
	0xdb, 0xfe, 0x30, 0x44, 0x07, 0xab, 0xf8, 0x3b, 0x98, 0x93, 0xa4, 0xdb, 0x97, 0xe5, 0x30, 0x06,
	0xf1, 0x52, 0xe6, 0x7f, 0xc8, 0x0a, 0x1f, 0xe1, 0xcd, 0x33, 0x96, 0xdc, 0xe9, 0xb7, 0xa1, 0x70,
	0xde, 0xb4, 0x47, 0x39, 0x6e, 0x56, 0xfc, 0x6d, 0xcc, 0x89, 0x4d, 0x3d, 0x3f, 0x49, 0xec, 0xab,
	0x02, 0x57, 0x12, 0x1a, 0xa5, 0x6a, 0xdc, 0xe7, 0xd9, 0x85, 0x2c, 0x0f, 0xe0, 0x2c, 0x9f, 0x16,
	0x33, 0xd8, 0x8a, 0xcc, 0xe0, 0x8f, 0x8c, 0x86, 0xa8, 0xb3, 0x47, 0x2e, 0xf7, 0x7c, 0x4b, 0xf2,
	0xa8, 0x77, 0x61, 0x26, 0x52, 0x46, 0xff, 0xc2, 0xc4, 0x6b, 0xe2, 0x4b, 0xcd, 0x60, 0x19, 0x4c,
	0xa4, 0x8b, 0x9b, 0x9d, 0x70, 0x22, 0xd3, 0x56, 0xb8, 0xb9, 0x97, 0xde, 0x52, 0x4a, 0x5f, 0xb2,
	0x30, 0x29, 0x44, 0xd1, 0x2b, 0xc8, 0x86, 0x61, 0x40, 0x4b, 0xc3, 0x86, 0x06, 0x52, 0xa6, 0x6a,
	0xe3, 0x8e, 0x43, 0x87, 0xfa, 0xd2, 0xbb, 0x6f, 0xbf, 0x3e, 0xa6, 0x17, 0xd0, 0xbc, 0xc9, 0x59,
	0xdd, 0x3c, 0xcf, 0x6f, 0x18, 0x31, 0xf4, 0x5e, 0x81, 0xd9, 0xe8, 0x53, 0x43, 0x57, 0x87, 0xf9,
	0x62, 0xc2, 0xa7, 0xae, 0x24, 0x83, 0xa4, 0xf4, 0x9a, 0x90, 0x5e, 0x41, 0xfa, 0x90, 0x74, 0x34,
	0x59, 0xe6, 0x61, 0x30, 0x85, 0x23, 0xf4, 0x49, 0x81, 0xb9, 0x91, 0x9c, 0xa0, 0x62, 0x92, 0x4e,
	0x34, 0x7f, 0xea, 0xea, 0x05, 0x90, 0xd2, 0xd6, 0x86, 0xb0, 0xb5, 0x86, 0x8a, 0x09, 0xb6, 0xaa,
	0x22, 0x66, 0x3d, 0x73, 0x3e, 0x4c, 0xc9, 0x9c, 0x20, 0x2d, 0xf6, 0x79, 0xf4, 0x13, 0xa8, 0x2e,
	0x8f, 0x3d, 0x97, 0xea, 0xeb, 0x42, 0xfd, 0x3a, 0xba, 0x36, 0xa4, 0x2e, 0x63, 0x26, 0x25, 0xcd,
	0x43, 0x11, 0x88, 0x23, 0xf4, 0x16, 0x66, 0xa3, 0x01, 0x1a, 0x1d, 0x4f, 0x4c, 0x1c, 0x47, 0xc7,
	0x13, 0x97, 0x41, 0x7d, 0x45, 0x38, 0xd1, 0xd0, 0x62, 0x9c, 0x93, 0xfe, 0xdd, 0x3f, 0x2b, 0x90,
	0x8b, 0x8b, 0x00, 0xba, 0x71, 0xb1, 0xa0, 0x84, 0x8e, 0x6e, 0xfe, 0x4d, 0xaa, 0xf4, 0x5b, 0xc2,
	0x99, 0x89, 0xd6, 0xe3, 0x9c, 0x55, 0x45, 0xcc, 0xaa, 0x35, 0xbf, 0x5a, 0x97, 0x7d, 0xd2, 0x6a,
	0xe5, 0xf1, 0xf1, 0xa9, 0xa6, 0x9c, 0x9c, 0x6a, 0xca, 0xcf, 0x53, 0x4d, 0xf9, 0x70, 0xa6, 0xa5,
	0x4e, 0xce, 0xb4, 0xd4, 0xf7, 0x33, 0x2d, 0xf5, 0xb2, 0x64, 0x3b, 0x7c, 0xbf, 0x53, 0x33, 0xea,
	0xb4, 0x65, 0xee, 0x79, 0x1d, 0xc6, 0x49, 0xe3, 0x69, 0x0b, 0x7b, 0x7c, 0x7b, 0x1f, 0x3b, 0xae,
	0x10, 0xe9, 0x96, 0xcd, 0x37, 0x3d, 0x25, 0xee, 0xb7, 0x09, 0xab, 0x65, 0xc5, 0xbf, 0xad, 0xfc,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x53, 0xd6, 0x2e, 0x63, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries all parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Distribution queries the canonical distribution for a day (YYYY-MM-DD).
	Distribution(ctx context.Context, in *QueryDistributionRequest, opts ...grpc.CallOption) (*QueryDistributionResponse, error)
	// DistributionVotes queries all submitted votes for a day (YYYY-MM-DD).
	DistributionVotes(ctx context.Context, in *QueryDistributionVotesRequest, opts ...grpc.CallOption) (*QueryDistributionVotesResponse, error)
	// Claimed reports whether a (date, nonce) reward has been claimed.
	Claimed(ctx context.Context, in *QueryClaimedRequest, opts ...grpc.CallOption) (*QueryClaimedResponse, error)
	// ClaimsByDate lists the reward nonces claimed for a day (YYYY-MM-DD).
	ClaimsByDate(ctx context.Context, in *QueryClaimsByDateRequest, opts ...grpc.CallOption) (*QueryClaimsByDateResponse, error)
	// ClaimTotalByCategory reports the cumulative claimed amount per category for a
	// day's distribution (YYYY-MM-DD).
	ClaimTotalByCategory(ctx context.Context, in *QueryClaimTotalByCategoryRequest, opts ...grpc.CallOption) (*QueryClaimTotalByCategoryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/distro.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Distribution(ctx context.Context, in *QueryDistributionRequest, opts ...grpc.CallOption) (*QueryDistributionResponse, error) {
	out := new(QueryDistributionResponse)
	err := c.cc.Invoke(ctx, "/distro.v1.Query/Distribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DistributionVotes(ctx context.Context, in *QueryDistributionVotesRequest, opts ...grpc.CallOption) (*QueryDistributionVotesResponse, error) {
	out := new(QueryDistributionVotesResponse)
	err := c.cc.Invoke(ctx, "/distro.v1.Query/DistributionVotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Claimed(ctx context.Context, in *QueryClaimedRequest, opts ...grpc.CallOption) (*QueryClaimedResponse, error) {
	out := new(QueryClaimedResponse)
	err := c.cc.Invoke(ctx, "/distro.v1.Query/Claimed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClaimsByDate(ctx context.Context, in *QueryClaimsByDateRequest, opts ...grpc.CallOption) (*QueryClaimsByDateResponse, error) {
	out := new(QueryClaimsByDateResponse)
	err := c.cc.Invoke(ctx, "/distro.v1.Query/ClaimsByDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClaimTotalByCategory(ctx context.Context, in *QueryClaimTotalByCategoryRequest, opts ...grpc.CallOption) (*QueryClaimTotalByCategoryResponse, error) {
	out := new(QueryClaimTotalByCategoryResponse)
	err := c.cc.Invoke(ctx, "/distro.v1.Query/ClaimTotalByCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries all parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Distribution queries the canonical distribution for a day (YYYY-MM-DD).
	Distribution(context.Context, *QueryDistributionRequest) (*QueryDistributionResponse, error)
	// DistributionVotes queries all submitted votes for a day (YYYY-MM-DD).
	DistributionVotes(context.Context, *QueryDistributionVotesRequest) (*QueryDistributionVotesResponse, error)
	// Claimed reports whether a (date, nonce) reward has been claimed.
	Claimed(context.Context, *QueryClaimedRequest) (*QueryClaimedResponse, error)
	// ClaimsByDate lists the reward nonces claimed for a day (YYYY-MM-DD).
	ClaimsByDate(context.Context, *QueryClaimsByDateRequest) (*QueryClaimsByDateResponse, error)
	// ClaimTotalByCategory reports the cumulative claimed amount per category for a
	// day's distribution (YYYY-MM-DD).
	ClaimTotalByCategory(context.Context, *QueryClaimTotalByCategoryRequest) (*QueryClaimTotalByCategoryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Distribution(ctx context.Context, req *QueryDistributionRequest) (*QueryDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distribution not implemented")
}
func (*UnimplementedQueryServer) DistributionVotes(ctx context.Context, req *QueryDistributionVotesRequest) (*QueryDistributionVotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributionVotes not implemented")
}
func (*UnimplementedQueryServer) Claimed(ctx context.Context, req *QueryClaimedRequest) (*QueryClaimedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Claimed not implemented")
}
func (*UnimplementedQueryServer) ClaimsByDate(ctx context.Context, req *QueryClaimsByDateRequest) (*QueryClaimsByDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimsByDate not implemented")
}
func (*UnimplementedQueryServer) ClaimTotalByCategory(ctx context.Context, req *QueryClaimTotalByCategoryRequest) (*QueryClaimTotalByCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTotalByCategory not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distro.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Distribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Distribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distro.v1.Query/Distribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Distribution(ctx, req.(*QueryDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DistributionVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDistributionVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DistributionVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distro.v1.Query/DistributionVotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DistributionVotes(ctx, req.(*QueryDistributionVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Claimed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClaimedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Claimed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distro.v1.Query/Claimed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Claimed(ctx, req.(*QueryClaimedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClaimsByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClaimsByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClaimsByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distro.v1.Query/ClaimsByDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClaimsByDate(ctx, req.(*QueryClaimsByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClaimTotalByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClaimTotalByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClaimTotalByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distro.v1.Query/ClaimTotalByCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClaimTotalByCategory(ctx, req.(*QueryClaimTotalByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "distro.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Distribution",
			Handler:    _Query_Distribution_Handler,
		},
		{
			MethodName: "DistributionVotes",
			Handler:    _Query_DistributionVotes_Handler,
		},
		{
			MethodName: "Claimed",
			Handler:    _Query_Claimed_Handler,
		},
		{
			MethodName: "ClaimsByDate",
			Handler:    _Query_ClaimsByDate_Handler,
		},
		{
			MethodName: "ClaimTotalByCategory",
			Handler:    _Query_ClaimTotalByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "distro/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDistributionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDistributionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDistributionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Distribution != nil {
		{
			size, err := m.Distribution.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDistributionVotesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDistributionVotesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDistributionVotesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDistributionVotesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDistributionVotesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDistributionVotesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryClaimedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClaimedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClaimedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClaimedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClaimedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClaimedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Claimed {
		i--
		if m.Claimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryClaimsByDateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClaimsByDateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClaimsByDateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClaimsByDateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClaimsByDateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClaimsByDateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nonces) > 0 {
		dAtA4 := make([]byte, len(m.Nonces)*10)
		var j3 int
		for _, num := range m.Nonces {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintQuery(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClaimTotalByCategoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClaimTotalByCategoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClaimTotalByCategoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClaimTotalByCategoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClaimTotalByCategoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClaimTotalByCategoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Totals) > 0 {
		for k := range m.Totals {
			v := m.Totals[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintQuery(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintQuery(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintQuery(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDistributionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Distribution != nil {
		l = m.Distribution.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDistributionVotesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDistributionVotesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryClaimedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovQuery(uint64(m.Nonce))
	}
	return n
}

func (m *QueryClaimedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Claimed {
		n += 2
	}
	return n
}

func (m *QueryClaimsByDateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryClaimsByDateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Nonces) > 0 {
		l = 0
		for _, e := range m.Nonces {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	return n
}

func (m *QueryClaimTotalByCategoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryClaimTotalByCategoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Totals) > 0 {
		for k, v := range m.Totals {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovQuery(uint64(len(k))) + 1 + len(v) + sovQuery(uint64(len(v)))
			n += mapEntrySize + 1 + sovQuery(uint64(mapEntrySize))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDistributionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDistributionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDistributionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Distribution == nil {
				m.Distribution = &Distribution{}
			}
			if err := m.Distribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDistributionVotesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDistributionVotesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDistributionVotesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDistributionVotesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDistributionVotesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDistributionVotesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, DistributionVote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClaimedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClaimedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClaimedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClaimedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClaimedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClaimedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Claimed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClaimsByDateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClaimsByDateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClaimsByDateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClaimsByDateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClaimsByDateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClaimsByDateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Nonces = append(m.Nonces, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Nonces) == 0 {
					m.Nonces = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Nonces = append(m.Nonces, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonces", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClaimTotalByCategoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClaimTotalByCategoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClaimTotalByCategoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClaimTotalByCategoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClaimTotalByCategoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClaimTotalByCategoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Totals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Totals == nil {
				m.Totals = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthQuery
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthQuery
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthQuery
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthQuery
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipQuery(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthQuery
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Totals[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
