// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: attestation/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AttestationCounter pairs a node address with one of its daily attestation
// counters for genesis import/export.
type AttestationCounter struct {
	// node_address is the node the counter belongs to.
	NodeAddress string `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	// counter is the node's rolling daily counter.
	Counter ActivityCounter `protobuf:"bytes,2,opt,name=counter,proto3" json:"counter"`
}

func (m *AttestationCounter) Reset()         { *m = AttestationCounter{} }
func (m *AttestationCounter) String() string { return proto.CompactTextString(m) }
func (*AttestationCounter) ProtoMessage()    {}
func (*AttestationCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_b798504a30b9686d, []int{0}
}
func (m *AttestationCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttestationCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttestationCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttestationCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationCounter.Merge(m, src)
}
func (m *AttestationCounter) XXX_Size() int {
	return m.Size()
}
func (m *AttestationCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationCounter.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationCounter proto.InternalMessageInfo

func (m *AttestationCounter) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *AttestationCounter) GetCounter() ActivityCounter {
	if m != nil {
		return m.Counter
	}
	return ActivityCounter{}
}

// GenesisState defines the attestation module genesis state. Attestation
// payloads are never stored in state; only the daily counters carry over.
type GenesisState struct {
	// Params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// rwa_counters are the per-node daily RWA attestation counters.
	RwaCounters []AttestationCounter `protobuf:"bytes,2,rep,name=rwa_counters,json=rwaCounters,proto3" json:"rwa_counters"`
	// rwu_counters are the per-node daily RWU attestation counters.
	RwuCounters []AttestationCounter `protobuf:"bytes,3,rep,name=rwu_counters,json=rwuCounters,proto3" json:"rwu_counters"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b798504a30b9686d, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRwaCounters() []AttestationCounter {
	if m != nil {
		return m.RwaCounters
	}
	return nil
}

func (m *GenesisState) GetRwuCounters() []AttestationCounter {
	if m != nil {
		return m.RwuCounters
	}
	return nil
}

func init() {
	proto.RegisterType((*AttestationCounter)(nil), "attestation.v1.AttestationCounter")
	proto.RegisterType((*GenesisState)(nil), "attestation.v1.GenesisState")
}

func init() { proto.RegisterFile("attestation/v1/genesis.proto", fileDescriptor_b798504a30b9686d) }

var fileDescriptor_b798504a30b9686d = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x6e, 0xfa, 0x30,
	0x10, 0xc6, 0x63, 0xf8, 0x8b, 0xbf, 0xea, 0xa0, 0x0e, 0x56, 0x55, 0x21, 0x54, 0x99, 0x94, 0x89,
	0x29, 0x16, 0x50, 0xa9, 0x63, 0x05, 0x0c, 0x1d, 0xba, 0xb4, 0xd0, 0xa9, 0x0b, 0x32, 0x89, 0x15,
	0x3c, 0x10, 0x23, 0xfb, 0x12, 0xe0, 0x2d, 0xfa, 0x58, 0x8c, 0x8c, 0x9d, 0x50, 0x05, 0x2f, 0x52,
	0x91, 0x18, 0x91, 0xc2, 0xd4, 0xed, 0xf4, 0x7d, 0xdf, 0xfd, 0xee, 0x4e, 0x87, 0xef, 0x38, 0x80,
	0x30, 0xc0, 0x41, 0xaa, 0x98, 0xa5, 0x6d, 0x16, 0x89, 0x58, 0x18, 0x69, 0xfc, 0xb9, 0x56, 0xa0,
	0xc8, 0x75, 0xc1, 0xf5, 0xd3, 0x76, 0xdd, 0x3b, 0x4b, 0x17, 0xed, 0xac, 0xa3, 0x7e, 0x13, 0xa9,
	0x48, 0x65, 0x25, 0x3b, 0x54, 0xb9, 0xda, 0x5c, 0x62, 0xd2, 0x3b, 0x45, 0x07, 0x2a, 0x89, 0x41,
	0x68, 0x72, 0x8f, 0xab, 0xb1, 0x0a, 0xc5, 0x98, 0x87, 0xa1, 0x16, 0xc6, 0xd4, 0x90, 0x87, 0x5a,
	0x57, 0x43, 0xf7, 0xa0, 0xf5, 0x72, 0x89, 0x3c, 0xe1, 0xff, 0x41, 0x9e, 0xae, 0x95, 0x3c, 0xd4,
	0x72, 0x3b, 0x0d, 0xff, 0xf7, 0x4a, 0x7e, 0x2f, 0x00, 0x99, 0x4a, 0x58, 0x59, 0x68, 0xff, 0xdf,
	0x7a, 0xdb, 0x70, 0x86, 0xc7, 0xae, 0xe6, 0x16, 0xe1, 0xea, 0x73, 0x7e, 0xd3, 0x08, 0x38, 0x08,
	0xf2, 0x80, 0x2b, 0x73, 0xae, 0xf9, 0x2c, 0x1f, 0xe7, 0x76, 0x6e, 0xcf, 0x81, 0xaf, 0x99, 0x6b,
	0x39, 0x36, 0x4b, 0x5e, 0x70, 0x55, 0x2f, 0xf8, 0xd8, 0x52, 0x4d, 0xad, 0xe4, 0x95, 0x5b, 0x6e,
	0xa7, 0x79, 0xb1, 0xcc, 0xc5, 0x91, 0x96, 0xe3, 0xea, 0x05, 0xb7, 0x8a, 0x85, 0x25, 0x27, 0x58,
	0xf9, 0xef, 0xb0, 0xe4, 0x08, 0xeb, 0xbf, 0xad, 0x77, 0x14, 0x6d, 0x76, 0x14, 0x7d, 0xef, 0x28,
	0xfa, 0xdc, 0x53, 0x67, 0xb3, 0xa7, 0xce, 0xd7, 0x9e, 0x3a, 0x1f, 0x8f, 0x91, 0x84, 0x69, 0x32,
	0xf1, 0x03, 0x35, 0x63, 0xef, 0x3a, 0x31, 0x20, 0xc2, 0xd1, 0x8c, 0x6b, 0x18, 0x4c, 0xb9, 0x8c,
	0x19, 0x98, 0x80, 0xa5, 0x5d, 0xb6, 0x2c, 0xfe, 0x90, 0xc1, 0x6a, 0x2e, 0xcc, 0xa4, 0x92, 0x3d,
	0xad, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x8a, 0x89, 0x9e, 0x1c, 0x02, 0x00, 0x00,
}

func (m *AttestationCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttestationCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttestationCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Counter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.NodeAddress) > 0 {
		i -= len(m.NodeAddress)
		copy(dAtA[i:], m.NodeAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.NodeAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RwuCounters) > 0 {
		for iNdEx := len(m.RwuCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RwuCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RwaCounters) > 0 {
		for iNdEx := len(m.RwaCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RwaCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AttestationCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Counter.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.RwaCounters) > 0 {
		for _, e := range m.RwaCounters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RwuCounters) > 0 {
		for _, e := range m.RwuCounters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AttestationCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttestationCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttestationCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Counter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RwaCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RwaCounters = append(m.RwaCounters, AttestationCounter{})
			if err := m.RwaCounters[len(m.RwaCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RwuCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RwuCounters = append(m.RwuCounters, AttestationCounter{})
			if err := m.RwuCounters[len(m.RwuCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
