// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: node/v1/query.proto

package types

import (
	"bytes"
	"compress/gzip"
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pbproto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoregistry"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// QueryCheckInRequest is the request type for the Query/CheckIn RPC.
type QueryCheckInRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Date    string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *QueryCheckInRequest) Reset()         { *m = QueryCheckInRequest{} }
func (m *QueryCheckInRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCheckInRequest) ProtoMessage()    {}
func (*QueryCheckInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_v1_query, []int{0}
}

func (m *QueryCheckInRequest) XXX_Unmarshal(b []byte) error { return m.Unmarshal(b) }
func (m *QueryCheckInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCheckInRequest.Marshal(b, m, deterministic)
	}
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *QueryCheckInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCheckInRequest.Merge(m, src)
}
func (m *QueryCheckInRequest) XXX_Size() int              { return m.Size() }
func (m *QueryCheckInRequest) XXX_DiscardUnknown()        { xxx_messageInfo_QueryCheckInRequest.DiscardUnknown(m) }
var xxx_messageInfo_QueryCheckInRequest proto.InternalMessageInfo

func (m *QueryCheckInRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}
func (m *QueryCheckInRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

// QueryCheckInResponse is the response type for the Query/CheckIn RPC.
type QueryCheckInResponse struct {
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *QueryCheckInResponse) Reset()         { *m = QueryCheckInResponse{} }
func (m *QueryCheckInResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCheckInResponse) ProtoMessage()    {}
func (*QueryCheckInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_v1_query, []int{1}
}

func (m *QueryCheckInResponse) XXX_Unmarshal(b []byte) error { return m.Unmarshal(b) }
func (m *QueryCheckInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCheckInResponse.Marshal(b, m, deterministic)
	}
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *QueryCheckInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCheckInResponse.Merge(m, src)
}
func (m *QueryCheckInResponse) XXX_Size() int              { return m.Size() }
func (m *QueryCheckInResponse) XXX_DiscardUnknown()        { xxx_messageInfo_QueryCheckInResponse.DiscardUnknown(m) }
var xxx_messageInfo_QueryCheckInResponse proto.InternalMessageInfo

func (m *QueryCheckInResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// fileDescriptor_node_v1_query holds the gzipped FileDescriptorProto for node/v1/query.proto.
var fileDescriptor_node_v1_query []byte

func init() {
	fdp := nodeV1QueryFDProto()

	b, err := pbproto.Marshal(fdp)
	if err != nil {
		panic(fmt.Sprintf("node/v1/query.proto: marshal descriptor: %v", err))
	}
	fileDescriptor_node_v1_query = mustGzipNodeQuery(b)

	proto.RegisterType((*QueryCheckInRequest)(nil), "node.v1.QueryCheckInRequest")
	proto.RegisterType((*QueryCheckInResponse)(nil), "node.v1.QueryCheckInResponse")
	proto.RegisterFile("node/v1/query.proto", fileDescriptor_node_v1_query)

	if fd, fdErr := protodesc.NewFile(fdp, protoregistry.GlobalFiles); fdErr == nil {
		_ = protoregistry.GlobalFiles.RegisterFile(fd)
	}
}

func nodeV1QueryFDProto() *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    pbproto.String("node/v1/query.proto"),
		Package: pbproto.String("node.v1"),
		Syntax:  pbproto.String("proto3"),
		Options: &descriptorpb.FileOptions{
			GoPackage: pbproto.String("github.com/TrustedSmartChain/tsc/v3/x/node/types"),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: pbproto.String("QueryCheckInRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:     pbproto.String("address"),
						Number:   pbproto.Int32(1),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						JsonName: pbproto.String("address"),
					},
					{
						Name:     pbproto.String("date"),
						Number:   pbproto.Int32(2),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						JsonName: pbproto.String("date"),
					},
				},
			},
			{
				Name: pbproto.String("QueryCheckInResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:     pbproto.String("block_height"),
						Number:   pbproto.Int32(1),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_UINT64.Enum(),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						JsonName: pbproto.String("blockHeight"),
					},
				},
			},
		},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name: pbproto.String("Query"),
				Method: []*descriptorpb.MethodDescriptorProto{
					{
						Name:       pbproto.String("CheckIn"),
						InputType:  pbproto.String(".node.v1.QueryCheckInRequest"),
						OutputType: pbproto.String(".node.v1.QueryCheckInResponse"),
					},
				},
			},
		},
	}
}

func mustGzipNodeQuery(b []byte) []byte {
	var buf bytes.Buffer
	w := gzip.NewWriter(&buf)
	if _, err := w.Write(b); err != nil {
		panic(err)
	}
	if err := w.Close(); err != nil {
		panic(err)
	}
	return buf.Bytes()
}

// gRPC client/server

var _ context.Context
var _ grpc.ClientConn

const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for the Query service.
type QueryClient interface {
	CheckIn(ctx context.Context, in *QueryCheckInRequest, opts ...grpc.CallOption) (*QueryCheckInResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CheckIn(ctx context.Context, in *QueryCheckInRequest, opts ...grpc.CallOption) (*QueryCheckInResponse, error) {
	out := new(QueryCheckInResponse)
	err := c.cc.Invoke(ctx, "/node.v1.Query/CheckIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for the Query service.
type QueryServer interface {
	CheckIn(context.Context, *QueryCheckInRequest) (*QueryCheckInResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct{}

func (*UnimplementedQueryServer) CheckIn(ctx context.Context, req *QueryCheckInRequest) (*QueryCheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.v1.Query/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CheckIn(ctx, req.(*QueryCheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _Query_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/v1/query.proto",
}

// Marshal

func (m *QueryCheckInRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCheckInRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCheckInRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCheckInResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCheckInResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCheckInResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

// Size

func (m *QueryCheckInRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCheckInResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

// Unmarshal

func (m *QueryCheckInRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCheckInRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCheckInRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryCheckInResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCheckInResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCheckInResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
